version: 1.0.0-{build}

image: Visual Studio 2017

clone_depth: 1

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cmd: echo Tada


