version: 1.0.0-{build}

image: Visual Studio 2017

clone_depth: 1

build_script:
  - cmd: echo Build started
  - cmd: set USER
  - cmd: systeminfo

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

